import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export type CertificateSignatoryInfo = {
  name: string;
  email: string;
  status: string;
  signedAt: string | null;
  signatureMethod: string | null;
};

export type CertificateAuditEventInfo = {
  action: string;
  createdAt: string;
};

export type CertificateOfCompletionInput = {
  envelopeId: string;
  title: string;
  status: string;
  completedAt: string | null;
  signatories: CertificateSignatoryInfo[];
  auditEvents: CertificateAuditEventInfo[];
};

const PAGE_SIZE: [number, number] = [595.28, 841.89]; // A4
const MARGIN = 50;

/** Renders a Certificate of Completion PDF for a completed e-sign envelope (FLW-DOC-003). */
export async function buildCertificateOfCompletionPdf(
  input: CertificateOfCompletionInput,
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage(PAGE_SIZE);
  let y = page.getHeight() - MARGIN;

  const drawLine = (
    text: string,
    options: { size?: number; bold?: boolean; gap?: number } = {},
  ) => {
    const size = options.size ?? 11;
    if (y < MARGIN + size) {
      page = pdfDoc.addPage(PAGE_SIZE);
      y = page.getHeight() - MARGIN;
    }
    page.drawText(text, {
      x: MARGIN,
      y,
      size,
      font: options.bold ? boldFont : font,
      color: rgb(0.12, 0.12, 0.12),
    });
    y -= options.gap ?? size + 8;
  };

  drawLine('Certificate of Completion', { size: 20, bold: true, gap: 30 });
  drawLine(`Envelope: ${input.title}`, { size: 13, bold: true, gap: 20 });
  drawLine(`Envelope ID: ${input.envelopeId}`);
  drawLine(`Status: ${input.status}`);
  drawLine(`Completed at (UTC): ${input.completedAt ?? 'N/A'}`, { gap: 26 });

  drawLine('Signatories', { size: 14, bold: true, gap: 18 });
  if (!input.signatories.length) {
    drawLine('No signatories recorded.', { gap: 20 });
  }
  for (const signatory of input.signatories) {
    drawLine(`${signatory.name} <${signatory.email}>`, { bold: true, gap: 14 });
    drawLine(
      `  Status: ${signatory.status} | Method: ${signatory.signatureMethod ?? 'n/a'} | Signed at: ${signatory.signedAt ?? 'n/a'}`,
      { size: 10, gap: 18 },
    );
  }

  y -= 8;
  drawLine('Audit Trail', { size: 14, bold: true, gap: 18 });
  if (!input.auditEvents.length) {
    drawLine('No audit events recorded.', { gap: 20 });
  }
  for (const event of input.auditEvents) {
    drawLine(`${event.createdAt} — ${event.action}`, { size: 10, gap: 14 });
  }

  y -= 10;
  drawLine(
    'Generated by Digitaro Polaris. Reflects the append-only e-sign audit trail (FLW-DOC-003).',
    { size: 9, gap: 16 },
  );

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes);
}
