import type { LucideIcon } from 'lucide-react';
import {
  Briefcase,
  Building2,
  CalendarDays,
  Circle,
  ClipboardList,
  Coins,
  DoorOpen,
  FileSignature,
  FileText,
  Gift,
  HelpCircle,
  Home,
  Inbox,
  LayoutDashboard,
  Receipt,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Target,
  User,
  UserPlus,
  Users,
  Wallet,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  home: Home,
  calendar: CalendarDays,
  hub: Inbox,
  me: User,
  leave: CalendarDays,
  policies: ClipboardList,
  compliance: ShieldCheck,
  audit: ScrollText,
  roles: Shield,
  documents: FileSignature,
  directory: Search,
  performance: Target,
  help: HelpCircle,
  security: Shield,
  sessions: Smartphone,
  invoices: Receipt,
  manager_cockpit: Briefcase,
  manager_calendar: CalendarDays,
  manager_performance: Target,
  hr_dashboard: LayoutDashboard,
  workers: Users,
  org: Building2,
  pre_boarding: Send,
  onboarding: UserPlus,
  separations: DoorOpen,
  leave_admin: CalendarDays,
  documents_register: FileText,
  templates: FileText,
  letterheads: FileText,
  setup: Settings,
  pay_runs: Wallet,
  benefits: Gift,
  statutory_rates: ShieldCheck,
  contractor_payments: Receipt,
  fx: Coins,
};

export function shellNavIcon(moduleId: string): LucideIcon {
  return ICONS[moduleId] ?? Circle;
}
